//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aksiyonlar
    {
        public int ID { get; set; }
        public string CBS_ID { get; set; }
        public string Proje_Turu { get; set; }
        public string Proje_Adi { get; set; }
        public string Cizim_Adi { get; set; }
        public string Telekom_Mud { get; set; }
        public string Santral { get; set; }
        public Nullable<double> Altyapi_Maliyeti { get; set; }
        public Nullable<double> Acik_Kazi { get; set; }
        public string Fider { get; set; }
        public string Trencher { get; set; }
        public string Kazser { get; set; }
        public Nullable<double> Yeralti_Guzergahincan { get; set; }
        public string Yeni_Havi_Guzergahtan { get; set; }
        public string Mevcut_Havai_Guzergahtan { get; set; }
        public string Kazser_Guzergahtan { get; set; }
        public string FTTC_OFSD_OFTK { get; set; }
        public Nullable<double> FTTB_3_48U_Kabin { get; set; }
        public Nullable<double> Aktarma { get; set; }
        public string Bina_ici_Kablolama { get; set; }
        public string Islem { get; set; }
        public Nullable<System.DateTime> Islem_Tarih { get; set; }
        public string Gerekce { get; set; }
        public string Kullanici { get; set; }
        public Nullable<System.DateTime> Baslangic_Tarih { get; set; }
        public Nullable<System.DateTime> Bitis_Tarih { get; set; }
        public Nullable<double> Proje_Sure { get; set; }
        public Nullable<double> Proje_Adet { get; set; }
        public Nullable<double> Proje_Sira { get; set; }
        public Nullable<double> Mukerrer { get; set; }
        public Nullable<double> Kalan_Sure { get; set; }
        public string Eski_Islem_Tarih { get; set; }
        public string Aktif_Islem { get; set; }
        public Nullable<double> Aktif_Sure { get; set; }
        public Nullable<double> Cezali_Gun_Sayisi { get; set; }
        public Nullable<double> Ceza_Tutari { get; set; }
        public string Tarih { get; set; }
        public string Proje_Genel_Durumu { get; set; }
        public Nullable<decimal> PROJE_REVIZE_BUTCE { get; set; }
        public Nullable<decimal> GERCEKLESEN_IMALAT_TUTARI { get; set; }
        public Nullable<double> Karsilastirma { get; set; }
    }
}
