//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilerleme
    {
        public int ID { get; set; }
        public string BOLGE_ADI { get; set; }
        public string IL_ADI { get; set; }
        public string SANTRAL_ADI { get; set; }
        public string PROJE_NO { get; set; }
        public string PROJE_ADI { get; set; }
        public string CIZIM_ADI { get; set; }
        public Nullable<double> CIZIM_ID { get; set; }
        public string PROJE_OZELLIGI { get; set; }
        public string CIZIM_ONAY_DURUMU { get; set; }
        public Nullable<double> RUHSAT { get; set; }
        public Nullable<double> MALZEME { get; set; }
        public Nullable<double> ALTYAPI { get; set; }
        public string FIBERNET_HP { get; set; }
        public string HIPERNET_HP { get; set; }
        public Nullable<double> ID2 { get; set; }
        public Nullable<double> OLT { get; set; }
        public Nullable<double> FTA { get; set; }
        public Nullable<double> OFTK { get; set; }
        public Nullable<double> T_1 { get; set; }
        public Nullable<double> T_11A { get; set; }
        public Nullable<double> T_11B { get; set; }
        public Nullable<double> T_13 { get; set; }
        public Nullable<double> T_15 { get; set; }
        public Nullable<double> T_21 { get; set; }
        public Nullable<double> T_3 { get; set; }
        public Nullable<double> T_5 { get; set; }
        public Nullable<double> T_6 { get; set; }
        public Nullable<double> T_7 { get; set; }
        public Nullable<double> T_9 { get; set; }
        public Nullable<double> SPLITTER { get; set; }
        public Nullable<double> MDU { get; set; }
        public Nullable<double> KTA { get; set; }
        public Nullable<double> IFTK { get; set; }
        public Nullable<double> T_23 { get; set; }
        public Nullable<double> T_17 { get; set; }
        public Nullable<double> T_19 { get; set; }
        public Nullable<double> FIBER_PLANLANAN { get; set; }
        public Nullable<double> BAKIR_PLANLAMA { get; set; }
        public Nullable<double> TRANSE_PLANLANAN { get; set; }
        public Nullable<double> GERCEKLESEN_ID { get; set; }
        public Nullable<double> GRC_OLT { get; set; }
        public Nullable<double> GRC_FTA { get; set; }
        public Nullable<double> GRC_OFTK { get; set; }
        public Nullable<double> GRC_T_1 { get; set; }
        public Nullable<double> GRC_T_11A { get; set; }
        public Nullable<double> GRC_T_11B { get; set; }
        public Nullable<double> GRC_T_13 { get; set; }
        public Nullable<double> GRC_T_15 { get; set; }
        public Nullable<double> GRC_T_21 { get; set; }
        public Nullable<double> GRC_T_3 { get; set; }
        public Nullable<double> GRC_T_5 { get; set; }
        public Nullable<double> GRC_T_6 { get; set; }
        public Nullable<double> GRC_T_7 { get; set; }
        public Nullable<double> GRC_T_9 { get; set; }
        public Nullable<double> GRC_SPLITTER { get; set; }
        public Nullable<double> GRC_MDU { get; set; }
        public Nullable<double> GRC_KTA { get; set; }
        public Nullable<double> GRC_IFTK { get; set; }
        public Nullable<double> GRC_T_23 { get; set; }
        public Nullable<double> GRC_T_17 { get; set; }
        public Nullable<double> GRC_T_19 { get; set; }
        public Nullable<double> TRANSE_ILERLEME { get; set; }
        public Nullable<double> FIBER_ILERLEME { get; set; }
        public Nullable<double> BAKIR_ILERLEME { get; set; }
        public string DEVAM_EDEN_PROJE_NO { get; set; }
        public string DEVAM_EDEN_PROJE_ADI { get; set; }
        public Nullable<double> BUTCE { get; set; }
        public Nullable<double> GERCEKLESEN_RUHSAT { get; set; }
        public Nullable<double> GERCEKLESEN_ALTYAPI { get; set; }
        public Nullable<double> GERCEKLESEN_MALZEME { get; set; }
        public string PYP_NO { get; set; }
        public string BASLANGIC_TARIH { get; set; }
        public string BITIS_TARIH { get; set; }
        public string TELEKOM_MUDURLUGU { get; set; }
        public string MAHALLE { get; set; }
        public Nullable<double> MAHALLE_UAVT { get; set; }
        public Nullable<double> PLANLANAN_KABIN_SAYISI { get; set; }
        public string FIILI_BASLANGIC { get; set; }
        public string FIILI_BITIS { get; set; }
        public string PROJE_DURUMU { get; set; }
        public Nullable<double> KURULU_KABIN { get; set; }
        public Nullable<double> SERVISE_ALINAN_KABIN { get; set; }
        public Nullable<double> PROJE_BUTCE { get; set; }
        public Nullable<double> PROJE_REVIZE_BUTCE { get; set; }
        public Nullable<double> GERCEKLESEN_IMALAT_TUTARI { get; set; }
        public Nullable<double> PSTN { get; set; }
        public Nullable<double> DSL { get; set; }
        public Nullable<double> IPTV { get; set; }
        public Nullable<double> TAMAMLANAN_HP { get; set; }
        public Nullable<double> TAMAMLANAN_HP_V2 { get; set; }
        public Nullable<double> PROJE_YILI { get; set; }
    }
}
