//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciHareket
    {
        public int ID { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Islem { get; set; }
        public string Gerekce { get; set; }
        public Nullable<System.DateTime> Islemtarih { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
